#import "JsonMapper.h"
#import "SplicerClient-Swift-Bridging-Header.h"

@implementation JsonMapper

- (RKObjectMapping *)mapComplexTypes
{
    //generated
    RKObjectMapping *SportsRootMapping = [RKObjectMapping mappingForClass:[ModelsSportsSportsRoot class]];
    [SportsRootMapping addAttributeMappingsFromDictionary:@{@"id":@"id__" }];
    RKObjectMapping *PersonMapping = [RKObjectMapping mappingForClass:[ModelsSportsPerson class]];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"id":@"id__" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"alias":@"alias_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"allowFacebookPosts":@"allowFacebookPosts_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"allowGameNotifications":@"allowGameNotifications_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"avatarContentType":@"avatarContentType_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"avatarFileName":@"avatarFileName_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"avatarFileSize":@"avatarFileSize_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"avatarId":@"avatarId_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"avatarUpdatedAt":@"avatarUpdatedAt_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"businessPhone":@"businessPhone_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"city":@"city_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"country":@"country_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"createdAt":@"createdAt_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"dateOfBirth":@"dateOfBirth_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"email2":@"email2_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"fax":@"fax_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"firstName":@"firstName_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"gender":@"gender_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"hiddenLastName":@"hiddenLastName_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"isAdmin":@"isAdmin_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"lastName":@"lastName_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"latitude":@"latitude_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"longitude":@"longitude_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"middleInitial":@"middleInitial_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"mobile":@"mobile_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"notes":@"notes_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"otherPhone":@"otherPhone_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"parentId":@"parentId_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"phone":@"phone_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"state":@"state_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"updatedAt":@"updatedAt_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"website":@"website_" }];
    [PersonMapping addAttributeMappingsFromDictionary:@{@"zip":@"zip_" }];
    RKObjectMapping *AccountsMapping = [RKObjectMapping mappingForClass:[ModelsSportsAccounts class]];
    [AccountsMapping addAttributeMappingsFromDictionary:@{@"id":@"id__" }];
    [AccountsMapping addAttributeMappingsFromDictionary:@{@"activationState":@"activationState_" }];
    [AccountsMapping addAttributeMappingsFromDictionary:@{@"activationToken":@"activationToken_" }];
    [AccountsMapping addAttributeMappingsFromDictionary:@{@"activationTokenExpiresAt":@"activationTokenExpiresAt_" }];
    [AccountsMapping addAttributeMappingsFromDictionary:@{@"createdAt":@"createdAt_" }];
    [AccountsMapping addAttributeMappingsFromDictionary:@{@"crossDomainCode":@"crossDomainCode_" }];
    [AccountsMapping addAttributeMappingsFromDictionary:@{@"cryptedPassword":@"cryptedPassword_" }];
    [AccountsMapping addAttributeMappingsFromDictionary:@{@"email":@"email_" }];
    [AccountsMapping addAttributeMappingsFromDictionary:@{@"loggedin":@"loggedin_" }];
    [AccountsMapping addAttributeMappingsFromDictionary:@{@"oldCryptedPassword":@"oldCryptedPassword_" }];
    [AccountsMapping addAttributeMappingsFromDictionary:@{@"rememberMeToken":@"rememberMeToken_" }];
    [AccountsMapping addAttributeMappingsFromDictionary:@{@"rememberMeTokenExpiresAt":@"rememberMeTokenExpiresAt_" }];
    [AccountsMapping addAttributeMappingsFromDictionary:@{@"resetPasswordEmailSentAt":@"resetPasswordEmailSentAt_" }];
    [AccountsMapping addAttributeMappingsFromDictionary:@{@"resetPasswordToken":@"resetPasswordToken_" }];
    [AccountsMapping addAttributeMappingsFromDictionary:@{@"salt":@"salt_" }];
    [AccountsMapping addAttributeMappingsFromDictionary:@{@"updatedAt":@"updatedAt_" }];
    RKObjectMapping *MembershipsMapping = [RKObjectMapping mappingForClass:[ModelsSportsMemberships class]];
    [MembershipsMapping addAttributeMappingsFromDictionary:@{@"id":@"id__" }];
    [MembershipsMapping addAttributeMappingsFromDictionary:@{@"createdAt":@"createdAt_" }];
    [MembershipsMapping addAttributeMappingsFromDictionary:@{@"membershipFields":@"membershipFields_" }];
    [MembershipsMapping addAttributeMappingsFromDictionary:@{@"membershipNumber":@"membershipNumber_" }];
    [MembershipsMapping addAttributeMappingsFromDictionary:@{@"updatedAt":@"updatedAt_" }];
    RKObjectMapping *MembershipSubscriptionsMapping = [RKObjectMapping mappingForClass:[ModelsSportsMembershipSubscriptions class]];
    [MembershipSubscriptionsMapping addAttributeMappingsFromDictionary:@{@"id":@"id__" }];
    [MembershipSubscriptionsMapping addAttributeMappingsFromDictionary:@{@"createdAt":@"createdAt_" }];
    [MembershipSubscriptionsMapping addAttributeMappingsFromDictionary:@{@"expiresOn":@"expiresOn_" }];
    [MembershipSubscriptionsMapping addAttributeMappingsFromDictionary:@{@"isActive":@"isActive_" }];
    [MembershipSubscriptionsMapping addAttributeMappingsFromDictionary:@{@"isOfflinePayment":@"isOfflinePayment_" }];
    [MembershipSubscriptionsMapping addAttributeMappingsFromDictionary:@{@"membershipId":@"membershipId_" }];
    [MembershipSubscriptionsMapping addAttributeMappingsFromDictionary:@{@"membershipOptionId":@"membershipOptionId_" }];
    [MembershipSubscriptionsMapping addAttributeMappingsFromDictionary:@{@"paidAt":@"paidAt_" }];
    [MembershipSubscriptionsMapping addAttributeMappingsFromDictionary:@{@"paidStatus":@"paidStatus_" }];
    [MembershipSubscriptionsMapping addAttributeMappingsFromDictionary:@{@"totalOwed":@"totalOwed_" }];
    [MembershipSubscriptionsMapping addAttributeMappingsFromDictionary:@{@"totalPaid":@"totalPaid_" }];
    [MembershipSubscriptionsMapping addAttributeMappingsFromDictionary:@{@"totalRefunds":@"totalRefunds_" }];
    [MembershipSubscriptionsMapping addAttributeMappingsFromDictionary:@{@"updatedAt":@"updatedAt_" }];
    [MembershipSubscriptionsMapping addAttributeMappingsFromDictionary:@{@"waiverInitials":@"waiverInitials_" }];
    RKObjectMapping *DivisionsMapping = [RKObjectMapping mappingForClass:[ModelsSportsDivisions class]];
    [DivisionsMapping addAttributeMappingsFromDictionary:@{@"id":@"id__" }];
    [DivisionsMapping addAttributeMappingsFromDictionary:@{@"name":@"name_" }];
    RKObjectMapping *TeamsMapping = [RKObjectMapping mappingForClass:[ModelsSportsTeams class]];
    [TeamsMapping addAttributeMappingsFromDictionary:@{@"id":@"id__" }];
    [TeamsMapping addAttributeMappingsFromDictionary:@{@"shortName":@"shortName_" }];
    RKObjectMapping *GamesMapping = [RKObjectMapping mappingForClass:[ModelsSportsGames class]];
    [GamesMapping addAttributeMappingsFromDictionary:@{@"id":@"id__" }];
    [GamesMapping addAttributeMappingsFromDictionary:@{@"awayBonusPoints":@"awayBonusPoints_" }];
    [GamesMapping addAttributeMappingsFromDictionary:@{@"awayLockerId":@"awayLockerId_" }];
    [GamesMapping addAttributeMappingsFromDictionary:@{@"boxTitle":@"boxTitle_" }];
    [GamesMapping addAttributeMappingsFromDictionary:@{@"context":@"context_" }];
    [GamesMapping addAttributeMappingsFromDictionary:@{@"createdAt":@"createdAt_" }];
    [GamesMapping addAttributeMappingsFromDictionary:@{@"gameNumber":@"gameNumber_" }];
    [GamesMapping addAttributeMappingsFromDictionary:@{@"homeBonusPoints":@"homeBonusPoints_" }];
    [GamesMapping addAttributeMappingsFromDictionary:@{@"homeLockerId":@"homeLockerId_" }];
    [GamesMapping addAttributeMappingsFromDictionary:@{@"name":@"name_" }];
    [GamesMapping addAttributeMappingsFromDictionary:@{@"officials":@"officials_" }];
    [GamesMapping addAttributeMappingsFromDictionary:@{@"scoringMethod":@"scoringMethod_" }];
    [GamesMapping addAttributeMappingsFromDictionary:@{@"startTime":@"startTime_" }];
    [GamesMapping addAttributeMappingsFromDictionary:@{@"status":@"status_" }];
    [GamesMapping addAttributeMappingsFromDictionary:@{@"updatedAt":@"updatedAt_" }];
    RKObjectMapping *TeamScoresMapping = [RKObjectMapping mappingForClass:[ModelsSportsTeamScores class]];
    [TeamScoresMapping addAttributeMappingsFromDictionary:@{@"id":@"id__" }];
    [TeamScoresMapping addAttributeMappingsFromDictionary:@{@"forfeited":@"forfeited_" }];
    [TeamScoresMapping addAttributeMappingsFromDictionary:@{@"goalsScored":@"goalsScored_" }];
    [TeamScoresMapping addAttributeMappingsFromDictionary:@{@"homeField":@"homeField_" }];
    [TeamScoresMapping addAttributeMappingsFromDictionary:@{@"rankPoints":@"rankPoints_" }];
    [TeamScoresMapping addAttributeMappingsFromDictionary:@{@"result":@"result_" }];
    [TeamScoresMapping addAttributeMappingsFromDictionary:@{@"seedIdentifier":@"seedIdentifier_" }];
    [TeamScoresMapping addAttributeMappingsFromDictionary:@{@"winLossTie":@"winLossTie_" }];
    RKObjectMapping *FacilitiesMapping = [RKObjectMapping mappingForClass:[ModelsSportsFacilities class]];
    [FacilitiesMapping addAttributeMappingsFromDictionary:@{@"id":@"id__" }];
    [FacilitiesMapping addAttributeMappingsFromDictionary:@{@"createdAt":@"createdAt_" }];
    [FacilitiesMapping addAttributeMappingsFromDictionary:@{@"description":@"description_" }];
    [FacilitiesMapping addAttributeMappingsFromDictionary:@{@"facilityType":@"facilityType_" }];
    [FacilitiesMapping addAttributeMappingsFromDictionary:@{@"name":@"name_" }];
    [FacilitiesMapping addAttributeMappingsFromDictionary:@{@"organizationId":@"organizationId_" }];
    [FacilitiesMapping addAttributeMappingsFromDictionary:@{@"updatedAt":@"updatedAt_" }];
    RKObjectMapping *LocationsMapping = [RKObjectMapping mappingForClass:[ModelsSportsLocations class]];
    [LocationsMapping addAttributeMappingsFromDictionary:@{@"id":@"id__" }];
    [LocationsMapping addAttributeMappingsFromDictionary:@{@"organizationId":@"organizationId_" }];
    [LocationsMapping addAttributeMappingsFromDictionary:@{@"name":@"name_" }];
    [LocationsMapping addAttributeMappingsFromDictionary:@{@"createdAt":@"createdAt_" }];
    [LocationsMapping addAttributeMappingsFromDictionary:@{@"updatedAt":@"updatedAt_" }];
    [LocationsMapping addAttributeMappingsFromDictionary:@{@"street":@"street_" }];
    [LocationsMapping addAttributeMappingsFromDictionary:@{@"zipCode":@"zipCode_" }];
    [LocationsMapping addAttributeMappingsFromDictionary:@{@"state":@"state_" }];
    [LocationsMapping addAttributeMappingsFromDictionary:@{@"city":@"city_" }];
    [LocationsMapping addAttributeMappingsFromDictionary:@{@"country":@"country_" }];
    [LocationsMapping addAttributeMappingsFromDictionary:@{@"lat":@"lat_" }];
    [LocationsMapping addAttributeMappingsFromDictionary:@{@"search":@"search_" }];
    [LocationsMapping addAttributeMappingsFromDictionary:@{@"phoneNumber":@"phoneNumber_" }];
    [LocationsMapping addAttributeMappingsFromDictionary:@{@"type":@"type_" }];
    [SportsRootMapping addPropertyMapping:[RKRelationshipMapping relationshipMappingFromKeyPath:@"person" toKeyPath:@"person_" withMapping:PersonMapping]];
    [SportsRootMapping addPropertyMapping:[RKRelationshipMapping relationshipMappingFromKeyPath:@"games" toKeyPath:@"games_" withMapping:GamesMapping]];
    [PersonMapping addPropertyMapping:[RKRelationshipMapping relationshipMappingFromKeyPath:@"accounts" toKeyPath:@"accounts_" withMapping:AccountsMapping]];
    [PersonMapping addPropertyMapping:[RKRelationshipMapping relationshipMappingFromKeyPath:@"memberships" toKeyPath:@"membershipList_" withMapping:MembershipsMapping]];
    [PersonMapping addPropertyMapping:[RKRelationshipMapping relationshipMappingFromKeyPath:@"divisions" toKeyPath:@"divisions_" withMapping:DivisionsMapping]];
    [PersonMapping addPropertyMapping:[RKRelationshipMapping relationshipMappingFromKeyPath:@"teams" toKeyPath:@"teams_" withMapping:TeamsMapping]];
    [MembershipsMapping addPropertyMapping:[RKRelationshipMapping relationshipMappingFromKeyPath:@"membershipsubscriptions" toKeyPath:@"membershipsubscriptions_" withMapping:MembershipSubscriptionsMapping]];
    [GamesMapping addPropertyMapping:[RKRelationshipMapping relationshipMappingFromKeyPath:@"divisions" toKeyPath:@"divisions_" withMapping:DivisionsMapping]];
    [GamesMapping addPropertyMapping:[RKRelationshipMapping relationshipMappingFromKeyPath:@"teamscores" toKeyPath:@"teamscores_" withMapping:TeamScoresMapping]];
    [GamesMapping addPropertyMapping:[RKRelationshipMapping relationshipMappingFromKeyPath:@"facilities" toKeyPath:@"facilities_" withMapping:FacilitiesMapping]];
    [TeamScoresMapping addPropertyMapping:[RKRelationshipMapping relationshipMappingFromKeyPath:@"teams" toKeyPath:@"teams_" withMapping:TeamsMapping]];
    [FacilitiesMapping addPropertyMapping:[RKRelationshipMapping relationshipMappingFromKeyPath:@"locations" toKeyPath:@"locations_" withMapping:LocationsMapping]];

    //end generated

    return PersonMapping;
}

@end
