//
//  FirstViewController.swift
//  SplicerClient-Ios
//
//  Created by Aaron Evans on 6/25/19.
//  Copyright © 2019 Aaron Evans. All rights reserved.
//

import UIKit

//class FirstViewController: UIViewController {//orig generated by xcode for new tabs app
//class FirstViewController: ViewController {//j2objc's: it demonstrates compiling java code
class FirstViewController: ExamplesFormViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }


}

